config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'workshop_templates#index'

  resources :workshops
  resources :workshop_templates

  namespace :admin do
    root 'workshop_templates#index'

    resources :workshops
    resources :workshop_templates
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/workshop.rb
# frozen_string_literal: true

class Workshop < ApplicationRecord
  belongs_to :workshop_template
end

app/models/workshop_template.rb
# frozen_string_literal: true

class WorkshopTemplate < ApplicationRecord
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO: Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/workshop_templates_controller.rb
# frozen_string_literal: true

module Admin
  class WorkshopTemplatesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/workshops_controller.rb
# frozen_string_literal: true

module Admin
  class WorkshopsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/workshop_templates_controller.rb
# frozen_string_literal: true

class WorkshopTemplatesController < ApplicationController
  before_action :set_workshop_template, only: %i[show edit update destroy]

  # GET /workshop_templates
  def index
    @workshop_templates = WorkshopTemplate.all
  end

  # GET /workshop_templates/1
  def show; end

  # GET /workshop_templates/new
  def new
    @workshop_template = WorkshopTemplate.new
  end

  # GET /workshop_templates/1/edit
  def edit; end

  # POST /workshop_templates
  def create
    @workshop_template = WorkshopTemplate.new(workshop_template_params)

    if @workshop_template.save
      redirect_to @workshop_template, notice: 'Workshop template was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /workshop_templates/1
  def update
    if @workshop_template.update(workshop_template_params)
      redirect_to @workshop_template, notice: 'Workshop template was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /workshop_templates/1
  def destroy
    @workshop_template.destroy
    redirect_to workshop_templates_url, notice: 'Workshop template was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_workshop_template
    @workshop_template = WorkshopTemplate.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def workshop_template_params
    params.require(:workshop_template).permit(:name, :description)
  end
end

app/controllers/workshops_controller.rb
# frozen_string_literal: true

class WorkshopsController < ApplicationController
  before_action :set_workshop, only: %i[show edit update destroy]

  # GET /workshops
  def index
    @workshops = Workshop.all
  end

  # GET /workshops/1
  def show; end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit; end

  # POST /workshops
  def create
    @workshop = Workshop.new(workshop_params)

    if @workshop.save
      redirect_to @workshop, notice: 'Workshop was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /workshops/1
  def update
    if @workshop.update(workshop_params)
      redirect_to @workshop, notice: 'Workshop was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /workshops/1
  def destroy
    @workshop.destroy
    redirect_to workshops_url, notice: 'Workshop was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_workshop
    @workshop = Workshop.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def workshop_params
    params.require(:workshop).permit(:name, :description, :workshop_template_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gathering</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/workshop_templates/_form.html.erb
<%= form_with(model: workshop_template, local: true) do |form| %>
  <% if workshop_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workshop_template.errors.count, "error") %> prohibited this workshop_template from being saved:</h2>

      <ul>
        <% workshop_template.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workshop_templates/edit.html.erb
<h1>Editing Workshop Template</h1>

<%= render 'form', workshop_template: @workshop_template %>

<%= link_to 'Show', @workshop_template %> |
<%= link_to 'Back', workshop_templates_path %>

app/views/workshop_templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workshop Templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workshop_templates.each do |workshop_template| %>
      <tr>
        <td><%= workshop_template.name %></td>
        <td><%= workshop_template.description %></td>
        <td><%= link_to 'Show', workshop_template %></td>
        <td><%= link_to 'Edit', edit_workshop_template_path(workshop_template) %></td>
        <td><%= link_to 'Destroy', workshop_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workshop Template', new_workshop_template_path %>

app/views/workshop_templates/new.html.erb
<h1>New Workshop Template</h1>

<%= render 'form', workshop_template: @workshop_template %>

<%= link_to 'Back', workshop_templates_path %>

app/views/workshop_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workshop_template.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workshop_template.description %>
</p>

<%= link_to 'Edit', edit_workshop_template_path(@workshop_template) %> |
<%= link_to 'Back', workshop_templates_path %>

app/views/workshops/_form.html.erb
<%= form_with(model: workshop, local: true) do |form| %>
  <% if workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
        <% workshop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :workshop_template_id %>
    <%= form.text_field :workshop_template_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workshops/edit.html.erb
<h1>Editing Workshop</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Show', @workshop %> |
<%= link_to 'Back', workshops_path %>

app/views/workshops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workshops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Workshop template</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workshops.each do |workshop| %>
      <tr>
        <td><%= workshop.name %></td>
        <td><%= workshop.description %></td>
        <td><%= workshop.workshop_template_id %></td>
        <td><%= link_to 'Show', workshop %></td>
        <td><%= link_to 'Edit', edit_workshop_path(workshop) %></td>
        <td><%= link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workshop', new_workshop_path %>

app/views/workshops/new.html.erb
<h1>New Workshop</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workshop.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workshop.description %>
</p>

<p>
  <strong>Workshop template:</strong>
  <%= @workshop.workshop_template_id %>
</p>

<%= link_to 'Edit', edit_workshop_path(@workshop) %> |
<%= link_to 'Back', workshops_path %>